name: Clash Subscription Builder

on:
  schedule:
    - cron: '*/30 * * * *'  # اجرا هر ۳۰ دقیقه
  push:
    paths:
      - 'configs/CollecSHEN.txt'
  workflow_dispatch:  # اجرا دستی

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pyyaml requests

      - name: Generate clash-sub.yaml
        run: |
          python3 refine.py

      - name: Commit & push generated YAML
        run: |
          git config --global user.name "ShervinBot"
          git config --global user.email "shervin@example.com"
          git add clash-sub.yaml
          git commit -m "🔄 Auto-generate clash-sub.yaml from CollecSHEN.txt" || echo "No changes"
          git push
